### ISSUE TITLE
Matrix addition

### ISSUE THREAD

**Issue by shreya1010svg** [acmpesuecc/laalibrary#3]
Perform addition of 2 matrices. Function prototype given.
`Matrix addition();`

**Comment by shreya1010svg** [comment]
There maybe some changes required in the prototype of the member function

**Comment by sbindal057** [comment]
I am interested

**Comment by jagriti-bhatia** [comment]
can i please work on this issue?

**Comment by preethika-ajay** [comment]
Hey, can I work on this?

**Comment by sreechand2002** [comment]
can i work on this
