### ISSUE TITLE
Modify constructor of `Matrix` Class to initialize null matrix without asking for user input

### ISSUE THREAD

**Issue by anirudhRowjee** [acmpesuecc/laalibrary#49]
**Is your feature request related to a problem? Please describe.**
It seems like it would be really difficult to work on a matrix bigger than 2x2 if you have to input all values when you initialize a matrix.

**Describe the solution you'd like**
Modification to the constructor of the `Matrix` class

**Describe alternatives you've considered**
Making a separate constructor method to do this

**Comment by shreya1010svg** [comment]
!bounty 10
