### ISSUE TITLE
Operator Overloading

### ISSUE THREAD

**Issue by anirudhRowjee** [acmpesuecc/laalibrary#52]
**Is your feature request related to a problem? Please describe.**
using the current methods to perform operations such as add, subtract, scalar multiplication and scalar division are extremely tedious

**Describe the solution you'd like**
Implement operator overloading, so instead of using member methods, we can do 
```cpp
Matrix m1(2, 2);
Matrix m2(2, 2);
Matrix res(2, 2, false);

res = m1 + m2
/* or 
res = m2 + m1
res = m2 - m1
*/

// scalar multiplication
res = 3 * m1
// or
res = m1 * 3

// scalar division
res = m1 / 3
```

**Describe alternatives you've considered**
none

**Comment by shreya1010svg** [comment]
!bounty 10
